app:
  cache_stream_max_length: 10000
  sync_delay: 2s
  buffer_size: 100
  save_timeout: 1s
  publish_timeout: 5s

mine:
  buffer_size: 20
  delay: 100ms

events:
  buffer_size: 50
  delay: 2s

factory:
  out_buffer_size: 20
  scaler:
    min_workers: 1
    max_workers: 10
    scale_up_threshold: 14
    scale_down_threshold: 4
    check_interval: 500ms

economy:
  contract_generation_interval: 30s
  contract_lifetime: 5m
  max_active_contracts: 3

  min_contract_reward: 50000
  max_contract_reward: 200000
  tax_rate_percent: 10

ingot:
  max_quality: 100

item:
  max_quality: 100
  quality_bonus: 10

ore:
  max_capacity: 100
  number_of_ores: 3
  materials:
    - iron
    - copper
    - gold
